---
title: "Topic: Innovation and Research Development Activities"
---

*Use at baseline and endline. Drawn from the Community Innovation Survey (CIS), the standard EU instrument for measuring firm-level innovation.*

---

### Product Innovation

**A product innovation is a new or improved good or service that differs significantly from the firm’s previous goods or services and which has been implemented on the market.

Include:
- significant changes to the design of a good
- digital goods or services


**During the last three years, did your company introduce any new or significantly improved goods?**
- Yes
- No

**If yes: How many?**
*(Open numeric field)*

**During the last [number] years, did your company introduce any new or significantly improved services?**
- Yes
- No

**If yes: How many?**
*(Open numeric field)*

**Since [year], did your enterprise introduce any new or improved products (goods or services) that were:**
- Not previously offered by any of your competitors
- Identical or very similar to products already offered by your competitors
- None of the above

**Who developed these product innovations?**
**(Select all that apply)*
- Your enterprise by itself
- Your enterprise together with other enterprises or organisations*
- Your enterprise by adapting or modifying products originally developed by other enterprises or organisations*
- Other enterprises or organisations*

**What share of your company's total turnover in the last financial year came from goods or services that were new or significantly improved in the last three years?**
- None
- Less than 5%
- 5–19%
- 20–49%
- 50% or more


### Process Innovation

A business process innovation is a new or improved business process for one or more business functions that differs significantly from the firm’s previous business processes and which has been implemented within the firm.

**During the last three years, did your company introduce any new or significantly improved processes?**
- Yes
- No

**If yes: How many?**
*(Open numeric field)*

**Since 2024, did your enterprise introduce any of the following types of new or improved processes that differ significantly from your previous processes?**
*(Select all that apply)*
- Methods for producing goods or providing services (including methods for developing goods or services)
- Logistics, delivery or distribution methods 
- Methods for information processing or communication
- Methods for accounting or other administrative operations
- Business practices for organising procedures or external relations
- Methods of organising work responsibility, decision making or human resource management
- Marketing methods for promotion, packaging, pricing, product placement or after sales services
- None of the above

**Who developed these process innovations?**
*(Select all that apply)*
- Your enterprise by itself
- Your enterprise together with other enterprises or organisations
- Your enterprise by adapting or modifying processes originally developed by other enterprises or organisations
- Other enterprises or organisations


### Innovation and R&D activities

'Innovation activity' includes all developmental, financial and commercial activities, undertaken by a firm, which are intended to or result in an innovation.
Research and Development (R&D): R&D comprise creative and systematic work undertaken in order to increase the stock of knowledge – including knowledge of humankind, culture and society – and to devise new applications of available knowledge.
R&D Performed in-house: R&D undertaken by your enterprise to create new knowledge or solve scientific or technical problems. Include current expenditures including labour costs and capital expenditures on buildings and equipment specifically for R&D)
R&D contracted out:  Your enterprise contracted-out R&D to other enterprises (include enterprises in your own group) or to public or private research organisations.

**Since [year], has your enterprise had any of the following types of innovation activities? (Activities leading to expenditures)**
*(Select all that apply)*
- Completed activities on product or process innovation
- Ongoing innovation activities at the end of 2025
- Abandoned innovation activities
- In-house research and development activities
- Contract-out R&D to other enterprises (include enterprises in your own group) or to public or private research organisations
- None of the above

**Since [year], has your firm performed in-house R&D continuously or occasionally?**
- Continuously (your firm had permanent R&D staff)
- Occasionally (as needed only)

**How much did your enterprise spend on innovation and R&D in [year] on each of the following items?**
*(Open numeric field, in [currency])*
- R&D performed in-house
- R&D contracted out to others
- All other innovation expenditures (i.e., excluding R&D)
  - Own personnel working on innovation
  - Services, materials, supplies purchased from others for innovation
  - Capital goods for innovation
  - Other expenditures for innovation

**How much (in [currency]) did your company spend on innovation (including R&D and other innovation activities) in [year]?**
*(Open numeric field, in [currency])*

**Which of the following best describes why your enterprise did not have more innovation activities during the three years from [year] to [year]:**
- A lack of resources prevented us from having more innovation activities. (e.g., lack of finance, qualified personnel, material)
- We decided not to innovate due to other reasons than a lack of resources. (e.g., strategic reasons; not the right time to innovate; other priorities; risks too high; low expected returns)
- We had no innovation activities because there was no need for innovation.

**How many full-time equivalent (FTE) staff were engaged in R&D or innovation-related  activities in your company in [year]**
*(Open numeric field)*

**Do you have a R&D department or a unit equivalent to it?**
- Yes
- No

### Constraints to innovation

**During 2025, how important were the following factors in hampering your enterprises’ decision to start innovation activities*, or its execution of innovation activities?**
*(Answer options: High, Medium, Low, Not a constraint)*
- Lack of internal finance for innovation
- Lack of credit or private equity
- Difficulties in obtaining public grants or subsidies 
- Costs too high
- Lack of skilled employees within your enterprise
- Lack of collaboration partners
- Lack of access to external knowledge
- Uncertain market demand for your ideas 
- Too much competition in your market
- Different priorities within your enterprise
- Not guaranteed to capture returns to innovation because easy for competitors to imitate


**Did your company receive any public funding for R&D activities in the last three years?**
*(Select all that apply)*
- Local or regional government grant
- National government grant
- EU funding (e.g. Horizon Europe, ERDF, ESF+)
- R&D tax credit or tax incentive
- Subsidised loan for R&D
- None

**If yes: How much?**
*(Open numeric field, in [currency])*
